services:
  kruidvat-notification:
    build: .
    environment:
      - PRODUCT_URL=${PRODUCT_URL}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - MAILGUN_FROM=${MAILGUN_FROM}
      - MAILGUN_TO=${MAILGUN_TO}
      - MAILGUN_ERROR_TO=${MAILGUN_ERROR_TO}
      - CRON=${CRON}
